spring:
  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver

    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://host.docker.internal:5432/users?currentSchema=users_scheme
    username: micro
    password: 1
